version: "3"

services:
  projetos:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
      placement:
        constraints: [node.role == worker]
    image: registry.gitlab.com/{your-image}:latest
    labels:
      stack: php
    ports:
      - 9000:80