version: "3"

services:
  portainer:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
      placement:
        constraints: [node.role == manager]
    image: portainer/portainer-ce
    labels:
      stack: monitoramento
    ports:
      - 8000:8000
      - 9090:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data: null